services:
  db:
    image: mysql/mysql-server:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=tree
      - MYSQL_ROOT_HOST=% 
      - MYSQL_DATABASE=issue_tracker
      - MYSQL_USER=issues
      - MYSQL_PASSWORD=issues
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
